// Actions
export const API_CALL_REQUEST = 'API_CALL_REQUEST';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';

export const API_CALL_LIB_REQUEST = 'API_CALL_LIB_REQUEST';
export const API_CALL_LIB_SUCCESS = 'API_CALL_LIB_SUCCESS';
export const API_CALL_LIB_FAILURE = 'API_CALL_LIB_FAILURE';

export const API_CALL_SEARCH_REQUEST = 'API_CALL_SEARCH_REQUEST';
export const API_CALL_SEARCH_SUCCESS = 'API_CALL_SEARCH_SUCCESS';
export const API_CALL_SEARCH_FAILURE = 'API_CALL_SEARCH_FAILURE';

export const API_ADD_TO_LIB_REQUEST = 'API_ADD_TO_LIB_REQUEST';
export const API_ADD_TO_LIB_SUCCESS = 'API_ADD_TO_LIB_SUCCESS';
export const API_ADD_TO_LIB_FAILURE = 'API_ADD_TO_LIB_FAILURE';

export const API_DELETE_VIDEO_REQUEST = 'API_DELETE_VIDEO_REQUEST';
export const API_DELETE_VIDEO_SUCCESS = 'API_DELETE_VIDEO_SUCCESS';
export const API_DELETE_VIDEO_FAILURE = 'API_DELETE_VIDEO_FAILURE';
